### ISSUE TITLE
Please Don't Mind!

### ISSUE THREAD

**Issue by SparkScratch-P** [SheepTester/web-server#4]
I wanna thank u a lot fo u helped me a lot.  are much more than a famous scratcher! U r still this down to earth! too difficult to believe. The difference is ur inside and outside of knowledge. I just wanna know how have u contributed to the Arctic code Vault? It's just a 'dream come true ' for me! I have never enjoyed speaking with someone more than I am doing with u! 
    I want to work with u and learn!

**Comment by SheepTester** [comment]
I think everyone who had a public repository by February 2020 had their repositories backed up automatically by GitHub for the [Arctic Code Vault](https://archiveprogram.github.com/):

> On 02/02/2020 GitHub captured a snapshot of every active public repository.

So being a contributor to the Arctic Code Vault just means I had an account with an active repository during February 2020.

**Comment by SparkScratch-P** [comment]
will it repeat next year also?

**Comment by SheepTester** [comment]
Don't think so; I think it was a one-time thing.
